### PR TITLE
Creates Main File

### PR DESCRIPTION
**Pull request by jwfehr**
This file houses the main function that will run all our other code. Includes comments where future code and changes will need to go

### CODE REVIEW

**Comment by jwfehr** [comment]
@ElyonsAnointed @mfborman @zwbce

**Comment by zwbce** [comment]
+1

**Comment by ghost** [comment]
Looks good. +1

**Comment by ghost** [comment]
I would add all of the "#include" statements from each of our other files.

**Comment by mfborman** [comment]
+1

**Pull request merged**
